all:
	gcc -Wall -Wextra -lm -o main main.c args.c stack.c read_data.c stack_utils.c introsort.c
debug:
	gcc -Wall -Wextra -lm -DDEBUG -o main main.c args.c stack.c read_data.c stack_utils.c introsort.c
